services:
  - type: web
    name: listen-to-anything
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: "20"
    headers:
      - path: /data/*.json
        name: Cache-Control
        value: public, max-age=3600
